import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";
import Menu from "@/components/Menu";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Lasko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${raleway.variable} antialiased bg-white `}
        style={{
          backgroundImage: 'url("bg.jpg")',
          backgroundSize: "1920px 912px",
        }}
      >
        <Menu />
        {children}
      </body>
    </html>
  );
}
